#!/bin/bash
#
# arch - part of the Arch-Setup project
# Copyright (C) 2025-2026, JustScott, development@justscott.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


#
# CLI tool to replace Arch-Setup and Arch-Configurations. It will
#  make the process of installing software and having them automatically
#  configured to my setup much easier.
#

# TODO: remove-setup, how to know whether to remove packages or not?
#   - for example, if the user setups gaming, and flatpak is installed,
#     how do I know they haven't started using flatpak now?

PROJECT_NAME="Arch-Setup"
SCRIPT_NAME="arch"

REQUIRED_PACKAGES=( \
    bash pacman \
    usermod gpasswd groups groupadd groupdel \
    grep cat \
    rfkill command \
)

INSTALLABLE_PACKAGES="\
    yay qutebrowser librewolf docker rust python flatpak \
"
SETUP_OPTIONS="\
    security user-scripts audio bluetooth \
    river gnome dwm dwl \
    gaming media qemu 3d-printing \
    embedded-rust rust-dioxus \
"

PACKAGE_INSTALLATION_LIBRARY=package_installation_library.sh
SETUP_INSTALLATION_LIBRARY=setup_installation_library.sh

PRETTY_OUTPUT_LIBRARY=pretty_output_library.sh

CONFIG_INSTALL_SCRIPT=install_configurations.sh

if ! echo "$@" | grep "add-to-path" &>/dev/null
then
    if ! [[ -d $arch_setup_directory ]]
    then
        printf "\n\e[31m%s\n%s\n%s\e[0m\n" \
            "[!] '\$arch_setup_directory' variable not set, or not set to" \
            "    the correct directory path. Either way, \`cd\` into the" \
            "    '$PROJECT_NAME' directory and run \`$SCRIPT_NAME add-to-path\`."
        exit $4
    fi
fi

add_to_path() {
    if [[ $(basename $(pwd)) == "$PROJECT_NAME" ]]
    then
        bashrc_line="export arch_setup_directory=\"$(pwd)\""

        if ! [[ -f "$HOME/.bashrc" ]]
        then
            if touch $HOME/.bashrc &>/dev/null
            then
                printf "\n\e[32m%s\e[0m\n" \
                    "Created the file $HOME/.bashrc"
            else
                printf "\n\e[31m%s\n%s\n%s\e[0m\n" \
                    "[!] Your user doesn't have a .bashrc in there \$HOME" \
                    "    directory, and attempts at creating one failed. A" \
                    "    $HOME/.bashrc file is required for this script."
                exit 7
            fi
        fi

        if grep "export arch_setup_directory=\"" $HOME/.bashrc \
            | grep "/$PROJECT_NAME\"$" &>/dev/null
        then
            # Replace existing variable with this new one
            sed -i \
                's,export arch_setup_directory=".*\/Arch-Setup"$,'"$bashrc_line"',' \
                $HOME/.bashrc
        else
            echo -e "\n$bashrc_line" >> $HOME/.bashrc
        fi

        # Check that the line was added without issue
        if grep "$bashrc_line" $HOME/.bashrc &>/dev/null
        then
            printf "\n\e[32m%s\e[0m\n" \
                "Added '$PROJECT_NAME' directory path to '.bashrc'"
        else
            printf "\n\e[31m%s\n%s\e[0m\n" \
                "[!] Could not add '$PROJECT_NAME' directory to your" \
                "    '.bashrc'... Check the files permissions and try again"
            exit 7
        fi

        # Create a .bin directory in $HOME for the arch script
        if ! [[ -f "./$SCRIPT_NAME" ]]
        then
            printf "\n\e[31m%s\n%s\e[0m\n" \
                "[!] './$SCRIPT_NAME' not found. Move to the '$PROJECT_NAME'" \
                "    directory containing the '$SCRIPT_NAME' script and try again"
            exit 8
        fi

        chmod u+x "./$SCRIPT_NAME"

        if ! [[ -d $HOME/.bin ]]
        then
            printf "\n\e[33m%s\e[0m" "[!] $HOME/.bin directory doesn't exit"

            if mkdir -p $HOME/.bin &>/dev/null
            then
                printf "\n\e[32m%s\e[0m" "Created $HOME/.bin"
            else
                printf "\n\e[31m%s\e[0m\n" "[!] Failed to create $HOME/.bin"
                exit 7
            fi
        fi

        if ! [[ -L "$HOME/.bin/$SCRIPT_NAME" ]]
        then
            if ln -s "$(pwd)/$SCRIPT_NAME" $HOME/.bin/ &>/dev/null
            then
                printf "\n\e[32m%s\e[0m\n" \
                    "Created softlink to '$SCRIPT_NAME' in $HOME/.bin"
            else
                printf "\n\e[31m%s\e[0m\n" \
                    "[!] Failed to create softlink to '$SCRIPT_NAME' in $HOME/.bin"
                exit 7
            fi
        fi

        path_modification="export PATH=\"\$PATH:$HOME/.bin\""

        if ! grep "^$path_modification$" $HOME/.bashrc &>/dev/null
        then
            echo -e "\n$path_modification" >> $HOME/.bashrc
        fi

        # Check that the line was added without issue
        if ! grep "$path_modification" $HOME/.bashrc &>/dev/null
        then
            printf "\n\e[31m%s\n%s\e[0m\n" \
                "[!] Could not edit path in '$HOME/.bashrc'..." \
                "    Check the files permissions and try again"
            exit 7
        fi
    else
        printf "\n\e[31m%s %s\e[0m\n" \
            "[!] Must be in the $PROJECT_NAME directory to" \
            "add it's path to your .bashrc"
        exit 1
    fi
}

check_library_files_exist() {
    if ! [[ -f "./$PRETTY_OUTPUT_LIBRARY" ]]
    then
        printf "\n\e[31m%s\e[0m\n" \
            "[!] Missing pretty output script. Cannot Proceed"
        exit 4
    fi
    if ! [[ -f "./$PACKAGE_INSTALLATION_LIBRARY" ]]
    then
        printf "\n\e[31m%s\e[0m\n" \
            "[!] Missing package installation scripts. Cannot Proceed"
        exit 4
    fi
    if ! [[ -f "./$SETUP_INSTALLATION_LIBRARY" ]]
    then
        printf "\n\e[31m%s\e[0m\n" \
            "[!] Missing setup installation scripts. Cannot Proceed"
        exit 4
    fi
}

check_packages()
{
    for tool in ${REQUIRED_PACKAGES[@]}
    do
        if ! { which $tool || type $tool; } &>/dev/null
        then
            printf "\n\e[31m%s\e[0m\n" "[!] Must install '$tool' for $SCRIPT_NAME to work"
            tools_not_installed=1
        fi
    done

    if ((tools_not_installed))
    then
        exit 6
    fi
}

display_help() {
    printf "\nUsage: $SCRIPT_NAME [COMMAND]"
    printf "\n\n  %s\n  %s" \
        "Simplifies Arch-Setup and Arch-Configurations into a single" \
        "CLI tool with many more automated features."

    printf "\n\nCommands:"
    printf "\n  %-15s %-1s" "add-to-path" \
        "Add the arch "
    printf "\n  %-15s %-1s" "install" "Install supported software"
    printf "\n  %-15s %-1s" "uninstall" "Cleanly uninstall supported software"
    printf "\n  %-15s %-1s" "setup" "Setup the system in specific ways"
    printf "\n  %-15s %-1s" "remove-setup" "Remove a setup"
    printf "\n  %-15s %-1s" "add-configs" \
        "Add config files to \$HOME/.config for supported software (runs automatically, you rarely need to run this command)"
    printf "\n  %-15s %-1s" "version" "Returns version information"

    printf "\n\n%s" \
        "(\`install\` is for tools you use directly: rust, docker, qutebrowser)"
    printf "\n%s" \
        "(\`setup\` is for set it and forget it defaults: security, river, bluetooth)"

    printf "\n\nBase Flags:"
    printf "\n  %-20s %-1s" "--version" "Returns version information"
    printf "\n  %-20s %-1s" "-h | --help" "Show this help message"

    printf "\n\nCommand Flags:"
    printf "\n  install:"
    printf "\n    %-20s %-1s" "-l | --list" "List installable software"
    printf "\n  uninstall:"
    printf "\n    %-20s %-1s" "-l | --list" "List installed software"
    printf "\n  setup:"
    printf "\n    %-20s %-1s" "-l | --list" "List available setup options"
    
    printf "\n\nExamples:"
    printf "\n  \`$SCRIPT_NAME install --list\`"
    printf "\n  \`$SCRIPT_NAME uninstall --list\`"
    printf "\n  \`$SCRIPT_NAME install qutebrowser\`"
    printf "\n  \`$SCRIPT_NAME install rust qemu docker\`"
    printf "\n  \`$SCRIPT_NAME uninstall qutebrowser\`"
    printf "\n  \`$SCRIPT_NAME setup river bluetooth\`"
    printf "\n  \`$SCRIPT_NAME setup security user-scripts\`"
    printf "\n  \`$SCRIPT_NAME remove-setup rust\`"
    printf "\n  \`$SCRIPT_NAME add-configs\`"

    printf "\n\nError Codes:"
    printf "\n  %-3s %-1s" "1" "Invalid command"
    printf "\n  %-3s %-1s" "2" "Package, setup, or preset doesn't exist"
    printf "\n  %-3s %-1s\n      %s" "3" \
        "Can't be uninstalled or removed as it doesn't exist or" \
        "isn't installed"
    printf "\n  %-3s %-1s" "4" "Missing source file for '$SCRIPT_NAME'"
    printf "\n  %-3s %-1s\n      %s" "5" \
        "Package, setup, or preset depends on one or many other" \
        "$SCRIPT_NAME commands being run first"
    printf "\n  %-3s %-1s" "6" "Missing package required by script"
    printf "\n  %-3s %-1s" "7" \
        "Missing system file or directory required by '$SCRIPT_NAME'"
    printf "\n  %-3s %-1s" "8" "Command run from the wrong directory"
}

install() {
    local \
        packages_to_install \
        FLAG_list_packages

    for arg in $@
    do
        case $arg in
            "-l" | "--list")
                [[ -n "$FLAG_list_packages" ]] && {
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] duplicated the list packages flag"
                    exit 1
                }
                FLAG_list_packages=1
            ;;
            *)
                # Support flags starting with '-' or "--" shouldn't reach
                # the catchall case
                if [[ $arg =~ ^-{1,2} ]]
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] The '$arg' flag isn't supported"
                    exit 1
                fi
                packages_to_install+=($arg)
            ;;
        esac
    done

    if ((FLAG_list_packages))
    then
        printf "\nPackages Available to Install:\n"
        for package_name in $INSTALLABLE_PACKAGES
        do
            echo "  - $package_name"
        done
        
        if [[ -n $packages_to_install ]]
        then
            printf "\n\e[31m%s %s\e[0m\n" \
                "[!] Cannot list installable packages" \
                "and install packages in the same command"
            exit 1
        fi

        exit 0
    fi

    for package_name in ${packages_to_install[@]}
    do
        if ! echo "$INSTALLABLE_PACKAGES" | grep "$package_name" &>/dev/null
        then
            printf "\n\e[31m%s\n%s\e[0m\n" \
                "[!] '$package_name' is not a supported package" \
                " - TIP: run \`arch install --list\` to see supported packages"
            exit 2
        fi
    done

    if check_library_files_exist
    then
        source ./$PACKAGE_INSTALLATION_LIBRARY
    else
        printf "\n\e[31m%s\n%s\e[0m\n" \
            "[!] Issue sourcing package installation library despite passing" \
            "    library file checks... This shouldn't happen"
    fi

    for package_name in ${packages_to_install[@]}
    do
        case $package_name in
            "yay")
                if ! install_yay
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to install yay"
                fi
            ;;
            "qutebrowser")
                if ! install_qutebrowser
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to install qutebrowser"
                fi
            ;;
            "librewolf")
                if ! install_librewolf
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to install librewolf"
                fi
            ;;
            "docker")
                if ! install_docker
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to install docker"
                fi
            ;;
            "python")
                if ! install_python
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to install python"
                fi
            ;;
            "rust")
                if ! install_rust
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to install rust"
                fi
            ;;
            "flatpak")
                if ! install_flatpak
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to install flatpak"
                fi
            ;;
            *)
                printf "\n\e[31m%s %s\e[0m\n" \
                    "[!] Chosen packages did not match installation case statement." \
                    "This shouldn't happen...stopping"
                exit 1
            ;;
        esac
    done
}

uninstall() {
    local \
        packages_to_uninstall \
        FLAG_list_packages

    for arg in $@
    do
        case $arg in
            "-l" | "--list")
                [[ -n "$FLAG_list_packages" ]] && {
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] duplicated the list installed packages flag"
                    exit 1
                }
                FLAG_list_packages=1
            ;;
            *)
                # Support flags starting with '-' or "--" shouldn't reach
                # the catchall case
                if [[ $arg =~ ^-{1,2} ]]
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] The '$arg' flag isn't supported"
                    exit 1
                fi
                packages_to_uninstall+=($arg)
            ;;
        esac
    done

    if ((FLAG_list_packages))
    then
        printf "\nInstalled Packages:\n"
        for package_name in $INSTALLABLE_PACKAGES
        do
            if ! { which yay || type yay; } &>/dev/null
            then
                if yay -Q $package_name &>/dev/null
                then
                    echo "  - $package_name"
                fi
            else
                if pacman -Q $package_name &>/dev/null
                then
                    echo "  - $package_name"
                fi
            fi
        done
        
        if [[ -n $packages_to_uninstall ]]
        then
            printf "\n\e[31m%s\e[0m" \
                "[!] Cannot list and uninstall packages in the same command"
            exit 1
        fi

        exit 0
    fi

    for package_name in ${packages_to_uninstall[@]}
    do
        if ! echo "$INSTALLABLE_PACKAGES" | grep "$package_name" &>/dev/null
        then
            printf "\n\e[31m%s\n%s\e[0m\n" \
                "[!] '$package_name' is not a supported package" \
                " - TIP: run \`arch uninstall --list\` to see supported packages"
            exit 3
        fi


        if ! { which yay || type yay; } &>/dev/null
        then
            if ! yay -Q $package_name &>/dev/null
            then
                printf "\n\e[31m%s\n%s %s\e[0m\n" \
                    "[!] '$package_name' is not installed" \
                    " - TIP: run \`arch uninstall --list\` to see" \
                    "installed packages"
                exit 3
            fi
        fi

        if ! pacman -Q $package_name &>/dev/null
        then
            echo -e "\n'$package_name' is not installed"
            echo -e "\nTIP: run \`arch uninstall --list\` to see installed packages"
            exit 3
        fi
    done

    if check_library_files_exist
    then
        source ./$PACKAGE_INSTALLATION_LIBRARY
    else
        printf "\n\e[31m%s\n%s\e[0m\n" \
            "[!] Issue sourcing package installation library despite passing" \
            "    library file checks... This shouldn't happen"
    fi

    for package_name in ${packages_to_uninstall[@]}
    do
        case $package_name in
            "yay")
                if ! uninstall_yay
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to uninstall yay"
                fi
            ;;
            "qutebrowser")
                if ! uninstall_qutebrowser
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to uninstall qutebrowser"
                fi
            ;;
            "librewolf")
                if ! uninstall_librewolf
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to uninstall librewolf"
                fi
            ;;
            "docker")
                if ! uninstall_docker
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to uninstall docker"
                fi
            ;;
            "python")
                if ! uninstall_python
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to uninstall python"
                fi
            ;;
            "rust")
                if ! uninstall_rust
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to uninstall rust"
                fi
            ;;
            "flatpak")
                if ! uninstall_flatpak
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to uninstall flatpak"
                fi
            ;;
            *)
                printf "\n\e[31m%s %s\e[0m\n" \
                    "[!] Chosen packages did not match uninstall case statement." \
                    "This shouldn't happen...stopping"
                exit 1
            ;;
        esac
    done
}

setup() {
    local \
        setups_chosen \
        FLAG_list_packages

    for arg in $@
    do
        case $arg in
            "-l" | "--list")
                [[ -n "$FLAG_list_packages" ]] && {
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] duplicated the list setups flag"
                    exit 1
                }
                FLAG_list_setups=1
            ;;
            *)
                # Support flags starting with '-' or "--" shouldn't reach
                # the catchall case
                if [[ $arg =~ ^-{1,2} ]]
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] The '$arg' flag isn't supported"
                    exit 1
                fi
                setups_chosen+=($arg)
            ;;
        esac
    done

    if ((FLAG_list_setups))
    then
        printf "\nAvailable Setup Options:\n"
        for setup_name in $SETUP_OPTIONS
        do
            echo "  - $setup_name"
        done

        if [[ -n $setups_chosen ]]
        then
            printf "\n\e[31m%s %s\e[0m\n" \
                "[!] Cannot list setup options and" \
                "set them up in the same command"
        fi

        exit 0
    fi

    for setup_name in ${setups_chosen[@]}
    do
        if ! echo "$SETUP_OPTIONS" | grep "$setup_name" &>/dev/null
        then
            printf "\n\n\e[31m%s\n\t%s\e[0m\n" \
                "[!] '$setup_name' is not a supported setup" \
                " - TIP: run \`arch setup --list\` to see supported setups"
            exit 2
        fi
    done

    if check_library_files_exist
    then
        source ./$SETUP_INSTALLATION_LIBRARY
    else
        printf "\n\e[31m%s\n%s\e[0m\n" \
            "[!] Issue sourcing setup library despite passing" \
            "    library file checks... This shouldn't happen"
    fi

    for setup_name in ${setups_chosen[@]}
    do
        case $setup_name in
            "user-scripts")
                if ! setup_user_scripts
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to setup: user-scripts"
                fi
            ;;
            "qemu")
                if ! setup_qemu
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to setup: qemu"
                fi
            ;;
            "gaming")
                if ! setup_gaming
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to setup: gaming"
                fi
            ;;
            "security")
                if ! setup_security
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to setup: security"
                fi
            ;;
            "audio")
                if ! setup_audio
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to setup: audio"
                fi
            ;;
            "bluetooth")
                if ! setup_bluetooth
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to setup: bluetooth"
                fi
            ;;
            "media")
                if ! setup_media
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to setup: media"
                fi
            ;;
            "embedded-rust")
                if ! setup_embedded_rust
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to setup: embedded-rust"
                fi
            ;;
            "rust-dioxus")
                if ! setup_rust_dioxus
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to setup: rust-dioxus"
                fi
            ;;
            "3d-printing")
                if ! setup_3d_printing
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to setup: 3d-printing"
                fi
            ;;
            *)
                printf "\e[31m%s %s\e[0m" \
                    "Chosen setups did not match setup case statement." \
                    "This shouldn't happen...stopping"
                exit 1
            ;;
        esac
    done
}

remove_setup() {
    local \
        setups_chosen \

    for arg in $@
    do
        case $arg in
            *)
                # Support flags starting with '-' or "--" shouldn't reach
                # the catchall case
                if [[ $arg =~ ^-{1,2} ]]
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] The '$arg' flag isn't supported"
                    exit 1
                fi
                setups_chosen+=($arg)
            ;;
        esac
    done

    for setup_name in ${setups_chosen[@]}
    do
        if ! echo "$SETUP_OPTIONS" | grep "$setup_name" &>/dev/null
        then
            printf "\n\e[31m%s\n%s\e[0m\n" \
                "[!] '$setup_name' is not a supported setup option" \
                " - TIP: run \`arch setup --list\` to see supported setup options"
            exit 3
        fi
    done

    if check_library_files_exist
    then
        source ./$SETUP_INSTALLATION_LIBRARY
    else
        printf "\n\e[31m%s\n%s\e[0m\n" \
            "[!] Issue sourcing setup library despite passing" \
            "    library file checks... This shouldn't happen"
    fi

    for setup_name in ${setups_chosen[@]}
    do
        case $setup_name in
            "user-scripts")
                if ! remove_setup_user_scripts
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to remove setup: user-scripts"
                fi
            ;;
            "qemu")
                if ! remove_setup_qemu
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to remove setup: qemu"
                fi
            ;;
            "gaming")
                if ! remove_setup_gaming
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to remove setup: gaming"
                fi
            ;;
            "security")
                if ! remove_setup_security
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to remove setup: security"
                fi
            ;;
            "audio")
                if ! remove_setup_audio
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to remove setup: audio"
                fi
            ;;
            "bluetooth")
                if ! remove_setup_bluetooth
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to remove setup: bluetooth"
                fi
            ;;
            "media")
                if ! remove_setup_media
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to remove setup: media"
                fi
            ;;
            "embedded-rust")
                if ! remove_setup_embedded_rust
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to remove setup: embedded-rust"
                fi
            ;;
            "rust-dioxus")
                if ! remove_setup_rust_dioxus
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to remove setup: rust-dioxus"
                fi
            ;;
            "3d-printing")
                if ! remove_setup_3d_printing
                then
                    printf "\n\e[31m%s\e[0m\n" \
                        "[!] Failed to remove setup: 3d-printing"
                fi
            ;;
            *)
                printf "\n\e[31m%s %s\e[0m\n" \
                    "[!] Chosen setup did not match remove setup case statement." \
                    "This shouldn't happen...stopping"
                exit 1
            ;;
        esac
    done
}

case $1 in
    "add-to-path")         add_to_path ${@:2};exit ;exit 00;;
esac

cd $arch_setup_directory

check_packages
check_library_files_exist

case $1 in
    "install")             install ${@:2};bash ./$CONFIG_INSTALL_SCRIPT;;
    "uninstall")           uninstall ${@:2};bash ./$CONFIG_INSTALL_SCRIPT;;
    "setup")               setup ${@:2};bash ./$CONFIG_INSTALL_SCRIPT;;
    "remove-setup")        remove_setup ${@:2};bash ./$CONFIG_INSTALL_SCRIPT;;
    "add-configs")         bash ./$CONFIG_INSTALL_SCRIPT;;
    "version"|"--version") echo "0.1.0";;
    "--help"|"-h") display_help;;
    *) 
        printf "\n\n - [ERROR] Invalid use of the \`$SCRIPT_NAME\` command -";
        display_help
        exit 1
        ;;
esac


