#!/bin/bash
#
# prevent-screen-sleep - part of the Arch-Setup project
# Copyright (C) 2023, Scott Wyman, development@scottwyman.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

#
# If audio's playing, prevent xscreensaver from locking the screen
#

while true; 
do
    sleep 4m # Wait 4 minutes in between loops
    
    # Check if there's any audio playing
    pactl list short sinks | grep RUNNING >/dev/null
    
    # If the audio is running, seset the screen timeout timer
    [[ $? == 0 ]] && xscreensaver-command --deactivate > /dev/null
done
