#!/bin/bash
#
# set-monitors - part of the Arch-Setup project
# Copyright (C) 2023, Scott Wyman, development@scottwyman.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


#
# Automatically configures your monitors from left to right based on the
#  number of arguments given. ( All in 1920x1080 )
#   
  
xrandr --output "$1" --mode 1920x1080           
  
last_display="$1"    
  
for ((i=2; i<=$#; i++))    
do                                                  
    xrandr --output "${!i}" --mode 1920x1080 --right-of "$last_display"           
    last_display="${!i}"    
done
