#!/bin/bash
# 
# update-status-bar - part of the Arch-Setup project
# Copyright (C) 2023, Scott Wyman, development@scottwyman.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


update-status-bar() {
    # Get all batteries with capacities
    batt_array=$(ls /sys/class/power_supply/*/capacity)
    # Take the first battery with a capacity value as the default
    batt_path=$(dirname ${batt_array[0]})
    batt_percentage=$(cat $batt_path/capacity)

    [[ "$(cat $batt_path/status 2> /dev/null)" == "Charging" ]] \
        && charging="+" \
        || charging="-"
    battery_display=" batt: $charging$batt_percentage% |"

    # 
    # Yes, ethernet is suppose to only show if wifi isn't connected to a network
    #
    network_display=""
    [[ $(nmcli d) =~ "ethernet " ]] && {
        for ethernet_interface in $(nmcli d | grep 'ethernet ' | awk '{print $1}')
        do
            connection_state=$(net $ethernet_interface state)
            ssid=$(net $ethernet_interface connection)    
            # If the ethernet interface is connected to a network
            [[ $ssid =~ "--" ]] || {
                network_display="eth:$connection_state:$ssid |"
                break
            }
        done
    }

    [[ $(nmcli d) =~ "wifi " ]] && {
        for wifi_interface in $(nmcli d | grep 'wifi ' | awk '{print $1}')
        do
            connection_state=$(net $wifi_interface state)
            ssid=$(net $wifi_interface connection)    
            # If the wifi interface is connected to a network
            [[ $ssid =~ "--" ]] || {
                network_display="wifi:$connection_state:$ssid |"
                break
            }
        done
    }

    xsetroot -name "bri: $(brightness) | vol: $(volume)% |$battery_display $network_display $(date +"%B %e %H:%M")"
}

update-status-bar
