#!/bin/bash
#
# pack - part of the Arch-Setup project
# Copyright (C) 2023, Scott Wyman, development@scottwyman.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


#
# Automatically backups all my files
#

CURRENT_PWD="$PWD"

calcurse --export > ~/.config/calcurse/calcurse.ical

# cd into home for relative paths
cd ~

tar -czf $CURRENT_PWD/app_backup.tar \
    .newsboat .config/{calcurse,picom,vimb,lf,nvim} \
    .scripts .ssh \
    .bashrc .bash_profile .xscreensaver .xinitrc .vimrc \
    Pictures/Wallpapers \
    .var/app/ca.hamaluik.Timecop/data/timecop.db \
    Documents/Notesnook

cd $CURRENT_PWD

# Encrypt the backup for transport
openssl enc -a -aes-256-cbc -pbkdf2 --iter 1000000 -in app_backup.tar -out app_backup.tar.aes 2> /dev/null

# Exit if the user provides two different encryption keys
if [[ $? != 0 ]]
then
    echo "Encryption keys don't match"
    shred -uz app_backup.tar
    exit
fi

# Remove the unencrypted .tar file
shred -uz app_backup.tar

# Compress the final encrypted archive file once more
gzip -f9 app_backup.tar.aes
