#!/bin/bash
#
# bashrc_extension - part of the Linux-Setup project
# Copyright (C) 2024-2026, JustScott, development@justscott.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Meant to be sourced by the $HOME/.bashrc file. This allows you to keep
#  private information in your .bashrc, and non-private information in here.

# if in a tty
[[ -z "$DISPLAY" && -z "$WAYLAND_DISPLAY" ]] && {
    alias samsung_tty="stty rows 33 cols 120 &>/dev/null"
    alias laptop_tty="stty rows 47 cols 141 &>/dev/null"

    # enable color
    export TERM=xterm-256color
}

export PAGER="bat --paging=always --style=plain"
export EDITOR=nvim
alias e=$EDITOR
export CALCURSE_PAGER="bat --paging=always --style=plain --language=markdown"

alias grep='grep --color=auto'
alias ls='ls --color=auto'

export HISTFILESIZE=10000
export HISTSIZE=10000
alias ehist='history -a;eval "$(hist_fzf)"'
alias hist="history -a;hist_fzf"

alias newsboat='newsboat -c ~/.config/newsboat/cache.db'

alias mf="man \$(ls /usr/share/man/man1 | awk -F. '{print \$1}' | fzf --reverse) 2>/dev/null"

alias service="ls /lib/systemd/system/ | fzf --reverse --preview 'systemctl status {}' --preview-window '70%'"

alias term=nvim_term;

if command -v qutebrowser &>/dev/null;
then
    export BROWSER=qutebrowser
fi

# pacman/yay + fzf
if command -v pacman &>/dev/null; then
    # Package list : list all installed packages
    alias pl="pacman -Qq | fzf --preview 'pacman -Qi {}' --layout=reverse --preview-window '70%'"
    # Package search (find) : list all packages   ( 'ps' is taken by system utility )
    alias pf="pacman -Slq | fzf --preview 'pacman -Si {}' --layout=reverse --preview-window '70%'"
fi
if command -v yay &>/dev/null; then
    # Package list : list all installed packages
    alias yl="yay -Qq | fzf --preview 'yay -Qi {}' --layout=reverse --preview-window '70%'"
    # Package search (find) : list all packages
    alias yf="yay -Slq | fzf --preview 'yay -Si {}' --layout=reverse --preview-window '70%'"
fi

# Saves any running VirtualMachines before shutting down
safe_shutdown() {
    if command -v calcurse &>/dev/null
    then
        if [[ -f $HOME/.local/share/calcurse/.calcurse.pid ]]
        then
            printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
                "You need to close calcurse first.">&2
            return 1
    fi
    fi

    if command -v virsh &>/dev/null
    then
        if command -v vm &>/dev/null
        then
            vm save --all
        fi
    fi

    return 0
}

shutdown_wrapper() {
    safe_shutdown || return 1

    echo ""
    # Gives the user so many seconds to cancel the shutdown 
    for i in {5..1}; do
        printf "\r%s \e[1;36m%s\e[0m" "Shutting Down In:" "$i"
        sleep 1
    done

    shutdown $@ 
}

alias shutdown=shutdown_wrapper

reboot_wrapper() {
    safe_shutdown || return 1

    echo ""
    # Gives the user so many seconds to cancel the reboot 
    for i in {5..1}; do
        printf "\r%s \e[1;36m%s\e[0m" "Rebooting In:" "$i"
        sleep 1
    done

    reboot $@
}

alias reboot=reboot_wrapper

hist_fzf() {
    # Removes duplicates using the hashmap
    declare -A hist_hashmap

    echo "$(tac $HOME/.bash_history | while IFS= read -r line
    do
        [[ -n "$line" ]] && {
            [[ -v hist_hashmap["$line"] ]] || {
                echo $line
                hist_hashmap["$line"]=""
            }
        }
    done | fzf --reverse)"
}

wttr() {
    if [[ -n "$LOCATION" ]]
    then
        curl -s wttr.in/$LOCATION?u
    else
        echo "Must set the \$LOCATION variable first!"
        return 1
    fi
}

spell() {
    word=$(echo $1 | tr '[:upper:]' '[:lower:]')
    html=$(curl -L --silent "https://duckduckgo.com/?q=spell+$word&ia=answer")

    echo $html | grep "appears to be spelled correctly" &>/dev/null && {
        echo "Spelled Correctly"; return 0; 
    } || { 
        alternatives=$(echo $html | sed -n 's/.*Suggestions:<\/i>\(.*\)<\/a>.*/\1/p' | sed 's/<[^>]*>//g')

        echo "Spelled wrong, possible alternative spellings: $alternatives" >&2

        return 1
    }
}

define() {
    word=$(echo $1 | tr '[:upper:]' '[:lower:]')
    spell "$word" >/dev/null && {
        uppercase_word=$(echo $word | tr '[:lower:]' '[:upper:]' )
        URL="https://www.merriam-webster.com/dictionary/$word"

        definition=$(curl -L --silent "$URL" \
            | grep --ignore-case "the meaning of $word is" | grep -o 'content=".*"' \
            | sed "s/content=//; s/The meaning of $uppercase_word is //; s/. How to use $word in a sentence.//" \
            | sed 's/"$//; s/"//' | sed 's/ Did you know?//')

        [[ -n "$definition" ]] && {
            echo "$definition"
            return 0 
        } || {
            echo "Spell right, but no definition found." >&2
            return 1
        }
    }

    return 1
}

# Easy daily journal stored in notes by date
j() {
    months_directory=$HOME/notes/Writing/Journal/$(date +"%Y")/$(date +"%B")
    mkdir -p $months_directory 2>/dev/null
    $EDITOR $months_directory/$(date +"%d").md
}

# TODO: Place blogs in future website github directory
blog() {
    blog_directory=$HOME/notes/Writing/Blog
    mkdir -p $blog_directory 2>/dev/null
    lf $blog_directory || {
        echo "Failed to open blog... is lf installed?"
        (exit 1)
    }
}

plan() {
    DIRECTORY="$HOME/notes"
    FILE_PATH="$DIRECTORY/plan.md"

    if ! [[ -d "$DIRECTORY" ]]
    then
        mkdir -p "$DIRECTORY" &>/dev/null
    fi

    $EDITOR "$FILE_PATH"
}

view_plan() {
    FILE_PATH="$HOME/notes/plan.md"

    if [[ -f "$FILE_PATH" ]]
    then
        bat "$FILE_PATH"
    else
        printf "\e[31m%s\e[0m" "File '$FILE_PATH' doesn't exist"
    fi
}

batt() {
    if ls /sys/class/power_supply/*/capacity &>/dev/null
    then
        for capacity_path in $(ls /sys/class/power_supply/*/capacity)
        do
            batt_path=$(dirname $(ls $capacity_path))
            batt_name=$(basename $batt_path)
            batt_percentage=$(cat $capacity_path)
            [[ "$(cat $batt_path/status 2> /dev/null)" == "Charging" ]] \
                && charging="+" \
                || charging="-"
            [[ $batt_percentage -gt 99 ]] && { batt_percentage=100; unset charging; } 
            echo "$(basename $batt_name): $charging$batt_percentage%"
        done
    else 
        echo "No Batteries Found">&2
        return 1
    fi
}

f() {
    fzf_path=$(find . -type d -o -type f | fzf --reverse)

    [[ -d $fzf_path ]] && lf "$fzf_path"
    [[ -f $fzf_path ]] && nvim "$fzf_path" -c "cd $(dirname "$fzf_path")"
}

p() {
    pass_command=$1

    if [[ -n "$2" ]]
    then
        printf "\e[31m%s\e[0m %s %s" "[Error]" \
            "\`p\` is a simple fzf wrapper. For multi word commands," \
            "use \`pass\`." >&2
        return 1
    fi

    fzf_password=$(find "${HOME}/.password-store/" \
        -type f -name "*.gpg" -printf '%P\n' \
        | sed 's/^\.\///; s/\.gpg$//' | fzf --reverse)

    if [[ -n "$fzf_password" ]]
    then
        if [[ "$pass_command" == 'c' ]]
        then
            pass_command="-c"
        fi
        pass $pass_command "$fzf_password"
    fi
}

space() {
    filesystem_type=$(stat -f -c "%T" /)

    [[ "$filesystem_type" == "btrfs" ]] && {
        size=$(btrfs filesystem usage / 2>/dev/null | grep "Device size:" | awk '{print $3}')
        used=$(btrfs filesystem usage / 2>/dev/null | grep "Device allocated:" | awk '{print $3}')
        available=$(btrfs filesystem usage / 2>/dev/null | grep "Device unallocated:" | awk '{print $3}')

        printf "  %-12s %-12s %-12s\n" "Size" "Used" "Avail"
        printf "%-12s %-12s %-12s\n" "$size" "$used" "$available"
    } || {
        [[ "$filesystem_type" == "ext4" || "$filesystem_type" == "ext2/ext3" ]] \
            && df -h / \
            || echo "Unsupported filesystem type: '$filesystem_type'"
    }
}

change_timezone() {
    new_timezone=$(timedatectl list-timezones | fzf --reverse)
    if [[ -n "$new_timezone" ]]; then
        sudo ln -sf /usr/share/zoneinfo/$new_timezone /etc/localtime
        sudo systemctl restart systemd-timesyncd
    fi
}

nvim_term() {
    if command -v nvim &>/dev/null && [[ $INSIDE_NVIM_TERM != true ]];
    then
        export INSIDE_NVIM_TERM=true
        exec nvim +'term' '+set nonumber norelativenumber' '+set laststatus=0' '+startinsert'
    fi
}

chat()
{
    ollama serve &>/dev/null &
    OLLAMA_PID=$!
    clear

    # Add cleanup function
    cleanup() {
        kill $OLLAMA_PID 2>/dev/null
        wait $OLLAMA_PID 2>/dev/null
    }

    # Ensure cleanup happens on exit
    trap cleanup EXIT SIGINT SIGTERM

    printf "\n\e[36m%s\e[0m\n" "Starting Ollama Server..."
    sleep 3 # Give server time to start

    models="$(ollama list | awk 'NR > 1 {print $1}')"

    if [[ -z "$models" ]]
    then
        printf "\n\e[31m%s\e[0m\n" "[!] No models available"
        cleanup
        return 1
    fi

    model="$(echo "$models" | fzf)"

    if [[ -z "$model" ]]
    then
        printf "\n\e[33m%s\e[0m\n" "No model chosen... Goodbye"
        cleanup
        return 1
    fi

    printf "\n\e[36m%s\e[0m\n" "Starting chat with $model..."
    ollama run $model

    cleanup
}

update_arch_iso() {
    PREVIOUS_DIRECTORY=$PWD
    ISO_DIRECTORY="$HOME/Documents/ISOs"
    ISO_URL="https://mirror.arizona.edu/archlinux/iso/latest/archlinux-x86_64.iso"
    ISO_FILENAME="archlinux-x86_64.iso"
    ISO_SHA_URL="https://mirror.umd.edu/archlinux/iso/latest/sha256sums.txt"
    ISO_SHA_FILENAME="arch_iso_sha256sums.txt"

    mkdir -p "$ISO_DIRECTORY" &>/dev/null
    cd "$ISO_DIRECTORY"

    printf "\n\e[36mDownloading the latest sha256sum file...\e[0m"
    if ! curl -L "$ISO_SHA_URL" -o $ISO_SHA_FILENAME &>/dev/null
    then
        cd $PREVIOUS_DIRECTORY
        return 1
    fi
    printf "\r\e[32mSuccessfully downloaded the latest sha256sum file.\n\e[0m"

    if [[ -f "$ISO_FILENAME" ]] && sha256sum --ignore-missing -c "$ISO_SHA_FILENAME" &>/dev/null
    then
        printf "\n\e[36mArch ISO is up-to-date\n\e[0m"
    else
        printf "\n\e[36mDownloading the latest ISO...\n\e[0m"
        if curl -L "$ISO_URL" -o $ISO_FILENAME
        then
            if sha256sum --ignore-missing -c $ISO_SHA_FILENAME
            then
                printf "\e[32mISO Downloaded and verified!\n\e[0m"
            else
                printf "\e[31m[!] Failed to verify ISO, may have failed to download entirely.\n\e[0m"
                cd $PREVIOUS_DIRECTORY
                return 1
            fi
        fi
    fi

    cd $PREVIOUS_DIRECTORY
}

help_cli() {
    FILE_PATH="$HOME/notes/Resources/Linux/cli.md"

    if [[ -f "$FILE_PATH" ]]
    then
        bat "$FILE_PATH"
    else
        printf "\e[31m%s\e[0m" "File '$FILE_PATH' doesn't exist"
    fi
}

edit_help_cli() {
    DIRECTORY="$HOME/notes/Resources/Linux"
    FILE_PATH="$DIRECTORY/cli.md"

    if ! [[ -d "$DIRECTORY" ]]
    then
        mkdir -p "$DIRECTORY" &>/dev/null
    fi

    $EDITOR "$FILE_PATH"
}

help_bash() {
    FILE_PATH="$HOME/notes/Resources/Linux/bash.md"

    if [[ -f "$FILE_PATH" ]]
    then
        bat "$FILE_PATH"
    else
        printf "\e[31m%s\e[0m" "File '$FILE_PATH' doesn't exist"
    fi
}

edit_help_bash() {
    DIRECTORY="$HOME/notes/Resources/Linux"
    FILE_PATH="$DIRECTORY/bash.md"

    if ! [[ -d "$DIRECTORY" ]]
    then
        mkdir -p "$DIRECTORY" &>/dev/null
    fi

    $EDITOR "$FILE_PATH"
}

help_rust() {
    FILE_PATH="$HOME/notes/Resources/Development/Languages/rust.md"

    if [[ -f "$FILE_PATH" ]]
    then
        bat "$FILE_PATH"
    else
        printf "\e[31m%s\e[0m" "File '$FILE_PATH' doesn't exist"
    fi
}

edit_help_rust() {
    DIRECTORY="$HOME/notes/Resources/Development/Languages"
    FILE_PATH="$DIRECTORY/rust.md"

    if ! [[ -d "$DIRECTORY" ]]
    then
        mkdir -p "$DIRECTORY" &>/dev/null
    fi

    $EDITOR "$FILE_PATH"
}

project() {
    PROJECTS_DIR=$HOME/notes/Projects

    if ! [[ -d $PROJECTS_DIR ]]
    then
        printf "\n\e[31m%s\e[0m\n" \
            "[!] Projects directory '$PROJECTS_DIR' doesn't exists"
        return 1
    fi

    ORIGINAL_DIR=$(pwd)
    cd $PROJECTS_DIR

    available_projects="$(find * -maxdepth 0 -type d 2>/dev/null)"

    if [[ $(printf "$available_projects" | wc -l) -eq 0 ]]
    then
        printf "\n\e[31m%s\e[0m\n" \
            "[!] No projects exists, try creating a project directory in '$PROJECTS_DIR'"
        return 1
    fi

    chosen_project="$(echo "$available_projects" | fzf)"

    if [[ -z "$chosen_project" ]]
    then
        printf "\n\e[33m%s\e[0m\n" \
            "[!] No project chosen... goodbye"
        cd $ORIGINAL_PWD
        return 0
    fi

    if [[ -n "$EDITOR" ]]
    then
        $EDITOR $PROJECTS_DIR/$chosen_project/plan.md
    else
        nano $PROJECTS_DIR/$chosen_project/plan.md
    fi

    cd $ORIGINAL_PWD
}
