#!/bin/bash
#
# pack - part of the Arch-Setup project
# Copyright (C) 2023, Scott Wyman, development@scottwyman.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

#
# Automatically backups all my files
#

CURRENT_PWD="$PWD"

cd $HOME

ACTION="Export ical from calcurse"
CAL_CONFIG="$HOME/.config/calcurse/calcurse.ical"
mkdir -p $HOME/.config/calcurse >/dev/null
cp $CAL_CONFIG $CAL_CONFIG.bak >/dev/null
calcurse --export > $CAL_CONFIG 2>>/tmp/packerrors.log \
    && echo "[SUCCESS] $ACTION" \
    || echo "[FAIL] $ACTION... wrote error log to /tmp/packerrors.log"

tar -czf $CURRENT_PWD/host_backup.tar \
    packed_notes.tar.aes \
    .scripts/ssh_scripts .config/{calcurse,picom,lf,nvim,newsboat} \
    .bashrc .bash_profile .xscreensaver \
    .xinitrc .vimrc \
    Documents/PasswordManagers Pictures/Wallpapers

cd $CURRENT_PWD

# Encrypt the backup for transport
openssl enc -a -aes-256-cbc -pbkdf2 --iter 1000000 -in host_backup.tar -out host_backup.tar.aes 2> /dev/null

# Exit if the user provides two different encryption keys
[[ $? != 0 ]] && {
    echo "Encryption keys don't match"
    shred -uz host_backup.tar
    exit
}

# Remove the unencrypted .tar file
shred -uz host_backup.tar

# Compress the final encrypted archive file once more
gzip -f9 host_backup.tar.aes
