#!/bin/bash
#
# min_browser - part of the Arch-Setup project
# Copyright (C) 2023, Scott Wyman, development@scottwyman.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

#
# Opens the provided URL in the appropriate program
#

URL="$1"

VIDEO_URLS=("youtube.com" "odysee.com" "mp4")
AUDIO_URLS=("mp3")
IMAGE_URLS=("jpeg" "jpg" "png")

# Loop through possible video URLs
for item in "${AUDIO_URLS[@]}"; do
    echo "$URL" | grep -q -i "$item" && { 
        { (which st || type st) && [[ -n $DISPLAY ]]; } &>/dev/null \
            && { st -e mpv --no-video "$URL"; exit 0; }  
    }
done

# Loop through possible video URLs
for item in "${VIDEO_URLS[@]}"; do
    echo "$URL" | grep -q -i "$item" && { 
        { which mpv || type mpv; } &>/dev/null \
            && { 
                { mpv "$URL" & } &>/dev/null
                exit 0
            }
    }
done

# Loop through possible image URLs
for item in "${IMAGE_URLS[@]}"; do
    echo "$URL" | grep -q -i "$item" && { 
        { which feh || type feh; } &>/dev/null \
            && { 
                { feh "$URL" & } &>/dev/null
                exit 0
            }
        
        { which mpv || type mpv; } &>/dev/null \
            && { 
                { mpv "$URL" & } &>/dev/null
                exit 0
            }
    }
done

# Open url with lynx or python-html2text if all the loops failed
{ which lynx || type lynx; } &>/dev/null && lynx $URL || {
    { which html2text || type html2text; } &>/dev/null && {
        bat --language=md <(html2text <(curl -L --silent "$URL"))
    }
}
