#!/bin/bash
#
# mpv_lynx - part of the Arch-Setup project
# Copyright (C) 2023, Scott Wyman, development@scottwyman.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

#
# Opens the provided URL in the appropriate program
#

URL="$1"

VIDEO_URLS=("youtube.com" "odysee.com" "mp4")
AUDIO_URLS=("mp3")

# Loop through possible video url strings
for item in "${AUDIO_URLS[@]}"; do
    [[ $URL =~ $item ]] && { 
        st -e mpv --no-video "$URL" 
        exit
    }
done

# Loop through possible video url strings
for item in "${VIDEO_URLS[@]}"; do
    [[ $URL =~ $item ]] && { 
        mpv "$URL" > /dev/null 2>&1 
        exit
    }
done

# Only open URL with lynx if lynx is installed
which lynx &>/dev/null && lynx $URL
