#!/bin/bash
#
# nt - part of the Arch-Setup project
# Copyright (C) 2023, Scott Wyman, development@scottwyman.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Open a new st terminal window, then open a terminal in neovim,
#  this allows for easier terminal interaction along with scrolling

if { which nvim || type nvim; } &>/dev/null
then
    nvim -c "set nonumber norelativenumber| set laststatus=0 | :startinsert | :term"
else
    echo -e "\n - Neovim isn't installed"
    exit 1
fi
