#!/bin/bash
#
# snap - part of the Arch-Setup project
# Copyright (C) 2023, Scott Wyman, development@scottwyman.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


#
# A package manager wrapper that uses btrfs snapper to track the changes made
#  on the subvolumes/filesystem during installation. This allows for cleaning
#  up any files or directories that a package may leave out of its uninstall
#  process. It also allows you to disable a package, essentially uninstalling
#  it from your system temporarily, and to re-enable that package as if it had
#  never been gone, keeping all your changes to its config files in tact.
#

get_configs() {
    CONFIGS=($(sudo snapper list-configs | awk 'NR>2 {print $1}'))

    [[ ${#CONFIGS[@]} -gt 0 ]] || {
        echo -e "\n - [ERROR] Must create a config before using snap"
        exit 3
    
    }
}

# Check that the required packages are installed
check_packages() {
    get_configs # Exits if no configs exist

    required_packages=(btrfs snapper)

    for package in ${required_packages[@]}; do 
        $package --version &>/dev/null || {
            echo -e "\n - [ERROR] $package must be installed - \n"
            missing_packages=true
        } 
    done

    [[ $missing_packages = true ]] && exit 3

    sudo -v
}

display_help() {
    echo -e "\nUsage: snap [COMMAND]"
    echo -e "\nA package manager wrapper using btrfs snapper snapshots to"
    echo -e " have better control over the packages on your system\n"

    echo "Commands:"
    printf "\t%-15s %-1s\n" "list" "displays a list of the packages installed via snap along with there state"
    printf "\t%-15s %-1s\n" "install" "creates a pre & post snapshot of the package installation"
    printf "\t%-15s %-1s\n" "uninstall" "undoes the changes between the pre & post snapshot, and deletes the snapshots"
    printf "\t%-15s %-1s\n" "disable" "un-does the changes between the pre & post snapshots"
    printf "\t%-15s %-1s\n" "enable" "re-does the changes betweem the pre & post snapshots"
    printf "\t%-15s %-1s\n" "upgrade" "Reinstalls the newest package version, replacing the old snapshot"
    printf "\t%-15s %-1s\n" "version" "Returns version information"

    echo -e "\nCommand Flags:\n"
    echo -e "\tlist:"
    printf "\t    %-20s\t %-1s\n" "-e | --enabled" "List enabled packages only"
    printf "\t    %-20s\t %-1s\n" "-d | --disabled" "List disabled packages only"
    printf "\t    %-20s\t %-1s\n" "-N | --non-snap" "List all packages not managed by snap"
    echo -e "\tinstall:"
    printf "\t    %-20s\t %-1s\n" "-y | --noconfirm" "Automatically answer default to all pacman prompts"
    echo -e "\tuninstall:"
    printf "\t    %-20s\t %-1s\n" "-y | --noconfirm" "Automatically answer default to all pacman prompts"
    printf "\t    %-20s\t %-1s\n" "-a | --all" "Uninstall all packages managed by snap"
    echo -e "\tenable:"
    printf "\t    %-20s\t %-1s\n" "-a | --all" "Disable all packages"
    echo -e "\tdisable:"
    printf "\t    %-20s\t %-1s\n" "-a | --all" "Enable all packages"
    echo -e "\tupgrade:"
    printf "\t    %-20s\t %-1s\n" "-y | --noconfirm" "Automatically answer default to all pacman prompts"
    printf "\t    %-20s\t %-1s\n" "-N | --non-snap" "Upgrade all system packages not managed by snap, or alone to upgrade specific packages"
    printf "\t    %-20s\t %-1s\n" "-e | --enabled" "Upgrade all enabled packages"
    printf "\t    %-20s\t %-1s\n" "-d | --disabled" "Upgrade all disabled packages"

    echo -e "\nExamples:"
    echo -e "\t\`snap list -N\`"
    echo -e "\t\`snap install -y go rustup python\`"
    echo -e "\t\`snap uninstall --noconfirm go rustup\`"
    echo -e "\t\`snap disable go python\`"
    echo -e "\t\`snap disable -a\`"
    echo -e "\t\`snap enable go\`"
    echo -e "\t\`snap upgrade python go -y\`"
    echo -e "\t\`snap upgrade --enabled\`"
    echo -e "\t\`snap upgrade --non-snap htop\`"
    echo -e "\t\`snap upgrade\`"

    echo -e "\nError Codes:"
    printf "\t%-3s %-1s\n" "1" "Invalid command"
    printf "\t%-3s %-1s\n" "2" "Package doesn't exist"
    printf "\t%-3s %-1s\n" "3" "Missing dependencies"

    echo ""
}

install_packages() {
    # unset flag variables before match, for safety
    local unset noconfirm_flag \
        skipped_command_input \

    #
    # Capture flags
    #
    for arg in "${@}";
    do
        case $arg in
            "--noconfirm" | "-y")
                [[ -n "$noconfirm_flag" ]] && {
                    echo -e "\n - [ERROR] duplicated the 'noconfirm' flag - \n"
                    exit 1
                }
                local noconfirm_flag="--noconfirm"
            ;;
            *) 
                [[ "$arg" == "install" && -z "$skipped_command_input" ]] && {
                    skipped_command_input=true
                    continue
                }

                local package_names+=($arg)
            ;;
        esac
    done
    
    [[ ${#package_names[@]} -lt 0 ]] && {
        echo -e "\n - [ERROR] must provide at least one package - \n"
        exit 1
    }

    pacman -Si ${package_names[@]} &>/dev/null || {
        echo "...failed to find all packages, updating package index..."
        sudo pacman -Si ${package_names[@]} >/dev/null || exit 2
    }

    for package in ${package_names[@]}
    do
        pacman -Q $package &>/dev/null && {
            echo "$package already installed... skipping"
            continue
        }
        list_packages $package | grep "$package" &>/dev/null && {
            echo "$package snapshot already exists, try enabling instead... skipping"
            continue
        }

        for config in ${CONFIGS[@]}
        do
            sudo snapper -c $config create -d "snap__$package" -t pre
        done

        [[ -n $noconfirm_flag ]] && {
            echo -n "...installing $package..."
            sudo pacman -S $noconfirm_flag $package &>/dev/null || {
                pre_number=$(sudo snapper -c $config list | awk '{print $1}' | tail -n 1)
                sudo snapper -c $config delete $pre_number
                echo -e "\n - [ERROR] pacman failed to install $package... stopping - \n"
                exit 2
            }
            echo "[DONE]"
        } || sudo pacman -S $package || {
            pre_number=$(sudo snapper -c $config list | awk '{print $1}' | tail -n 1)
            sudo snapper -c $config delete $pre_number
            exit 2
        }

        for config in ${CONFIGS[@]}
        do
            # We can assume that the most recent snapshot was the one we created
            pre_number=$(sudo snapper -c $config list | awk '{print $1}' | tail -n 1)
            sudo snapper -c $config create -d "snap__$package" \
                -t post --pre-number $pre_number 
        done
    done
}

uninstall_packages() {
    # unset flag variables before match, for safety
    local unset skipped_command_input \
        noconfirm_flag \
        all_flag

    #
    # Capture flags
    #
    for arg in "${@}";
    do
        case $arg in
            "--noconfirm" | "-y")
                [[ -n "$noconfirm_flag" ]] && {
                    echo -e "\n - [ERROR] duplicated the 'noconfirm' flag - \n"
                    exit 1
                }
                local noconfirm_flag="--noconfirm"
            ;;
            "--all" | "-a")
                [[ -n "$all_flag" ]] && {
                    echo -e "\n - [ERROR] duplicated the 'all' flag - \n"
                    exit 1
                }
                local all_flag=true
            ;;
            *) 
                [[ "$arg" == "uninstall" && -z "$skipped_command_input" ]] && {
                    skipped_command_input=true
                    continue
                }

                local package_names+=($arg)
            ;;
        esac
    done

    [[ $all_flag == true ]] && {
        populate_enabled_disabled_all
        package_names+=(${all_snap_packages[@]})
    }

    [[ ${#package_names[@]} -lt 0 ]] && {
        echo -e "\n - [ERROR] must provide at least one package - \n"
        exit 1
    }

    # Uninstall to remove any files created after installation that pacman
    #  was instructed to delete
    #
    enable_packages ${package_names[@]}
    for package in ${package_names[@]}
    do
        [[ -n $noconfirm_flag ]] && {
            echo -n "...uninstalling $package..."
            sudo pacman -R $noconfirm_flag $package &>/dev/null || {
                echo -e "\n - [ERROR] pacman failed to uninstall $package... stopping - \n"
                exit 2
            }
            echo "[DONE]"
        } || {
            sudo pacman -R $package || exit 2
        }
    done
    
    disable_packages ${package_names[@]}

    for package in ${package_names[@]}
    do
        for config in ${CONFIGS[@]}
        do
            sudo snapper -c $config list | grep "snap__$package" | while IFS= read -r line   
            do
                snapshot_number=$(echo $line | awk '{print $1}')
                sudo snapper -c $config delete $snapshot_number
            done

            sudo snapper -c $config list | grep "snap_wrap-disable__$package" | while IFS= read -r line   
            do
                snapshot_number=$(echo $line | awk '{print $1}')
                sudo snapper -c $config delete $snapshot_number
            done
        done
    done
}

disable_packages() {
    # unset flag variables before match, for safety
    local unset skipped_command_input \
        all_flag

    #
    # Capture flags
    #
    for arg in "${@}";
    do
        case $arg in
            "--all" | "-a")
                [[ -n "$all_flag" ]] && {
                    echo -e "\n - [ERROR] duplicated the 'all' flag - \n"
                    exit 1
                }
                local all_flag=true
            ;;
            *) 
                [[ "$arg" == "disable" && -z "$skipped_command_input" ]] && {
                    skipped_command_input=true
                    continue
                }

                local package_names+=($arg)
            ;;
        esac
    done

    [[ $all_flag == true ]] && {
        populate_enabled_disabled_all
        package_names+=(${all_snap_packages[@]})
    }

    [[ ${#package_names[@]} -lt 0 ]] && {
        echo -e "\n - [ERROR] must provide at least one package - \n"
        exit 1
    }

    for package in ${package_names[@]}
    do
        list_packages | grep "$package" &>/dev/null || {
            echo "'$package' doesn't exist... skipping"
            continue
        }

        for config in ${CONFIGS[@]}
        do
            # Create a wrapper to prevent erasing user made changes to things like config files
            sudo snapper -c $config create -d "snap_wrap-disable__$package" --type pre

            sudo snapper -c $config list | grep "snap__$package" | sort -n | while IFS= read -r line   
            do

                snapshot_numbers+=($(echo $line | awk '{print $1}'))
                [[ ${#snapshot_numbers[@]} == 2 && ${snapshot_numbers[0]} -lt ${snapshot_numbers[1]} ]] && {
                    sudo snapper -c $config undochange "${snapshot_numbers[0]}..${snapshot_numbers[1]}" &>/dev/null
                    snapshot_numbers=()
                }

            done

            pre_number=$(sudo snapper -c $config list | awk '{print $1}' | tail -n 1)
            sudo snapper -c $config create -d "snap_wrap-disable__$package" \
                -t post --pre-number $pre_number 
        done
    done
}

enable_packages() {
    # unset flag variables before match, for safety
    local unset skipped_command_input \
        all_flag \

    #
    # Capture flags
    #
    for arg in "${@}";
    do
        case $arg in
            "--all" | "-a")
                [[ -n "$all_flag" ]] && {
                    echo -e "\n - [ERROR] duplicated the 'all' flag - \n"
                    exit 1
                }
                local all_flag=true
            ;;
            *) 
                [[ "$arg" == "enable" && -z "$skipped_command_input" ]] && {
                    skipped_command_input=true
                    continue
                }

                local package_names+=($arg)
            ;;
        esac
    done

    [[ $all_flag == true ]] && {
        populate_enabled_disabled_all
        package_names+=(${all_snap_packages[@]})
    }

    [[ ${#package_names[@]} -lt 0 ]] && {
        echo -e "\n - [ERROR] must provide at least one package - \n"
        exit 1
    }

    for package in ${package_names[@]}
    do
        list_packages | grep "$package" &>/dev/null || {
            echo "'$package' doesn't exist... skipping"
            continue
        }

        for config in ${CONFIGS[@]}
        do
            sudo snapper -c $config list | grep "snap_wrap-disable__$package" | sort -n | while IFS= read -r line   
            do
                snapshot_numbers+=($(echo $line | awk '{print $1}'))
                [[ ${#snapshot_numbers[@]} == 2 && ${snapshot_numbers[0]} -lt ${snapshot_numbers[1]} ]] && {
                    sudo snapper -c $config undochange "${snapshot_numbers[0]}..${snapshot_numbers[1]}" &>/dev/null
                    sudo snapper -c $config delete ${snapshot_numbers[@]}
                    unset snapshot_numbers
                }
            done
        done
    done
}

upgrade_packages() {
    # unset flag variables before match, for safety
    local unset noconfirm_flag \
        skipped_command_input \
        enabled_flag \
        disabled_flag \
        non_snap_flag \

    #
    # Capture flags
    #
    for arg in "${@}";
    do
        case $arg in
            "--noconfirm" | "-y")
                [[ -n "$noconfirm_flag" ]] && {
                    echo -e "\n - [ERROR] duplicated the 'noconfirm' flag - \n"
                    exit 1
                }
                local noconfirm_flag="--noconfirm"
            ;;
            "--non-snap" | "-N")
                [[ -n "$non_snap_flag" ]] && {
                    echo -e "\n - [ERROR] duplicated the 'non-snap' flag - \n"
                    exit 1
                }
                local non_snap_flag=true
            ;;
            "--enabled" | "-e")
                [[ -n "$enabled_flag" ]] && {
                    echo -e "\n - [ERROR] duplicated the 'enabled' flag - \n"
                    exit 1
                }
                local enabled_flag=true
            ;;
            "--disabled" | "-d")
                [[ -n "$disabled_flag" ]] && {
                    echo -e "\n - [ERROR] duplicated the 'disabled' flag - \n"
                    exit 1
                }
                local disabled_flag=true
            ;;
            *) 
                [[ "$arg" == "upgrade" && -z "$skipped_command_input" ]] && {
                    skipped_command_input=true
                    continue
                }

                local package_names+=($arg)
            ;;
        esac
    done

    [[ $non_snap_flag == true ]] && {
        [[ -n $package_names ]] && {
            sudo pacman -Sy $noconfirm_flag ${package_names[@]} && return 0 || return 2
        } || {
            packages=($(snap list -e | awk '{print $1}'))

            [[ -n $packages ]] && {
                pacman_args="--ignore $(echo ${packages[@]} | tr '[:blank:]' ',')"

                sudo pacman -Syu $noconfirm_flag $pacman_args && return 0 || return 2
            }
        }
    } || {
        populate_enabled_disabled_all
        local local_disabled_packages=(${disabled_packages[@]})

        [[ $enabled_flag == true ]] && flagged_package_names=(${enabled_packages[@]})

        [[ $disabled_flag == true ]] && flagged_package_names=(${disabled_packages[@]})

        [[ -z $enabled_flag && -z $disabled_flag ]] && {
            [[ -z $package_names ]] && package_names=(${all_snap_packages[@]})
        }

        package_names+=(${flagged_package_names[@]})

        echo ${package_names[@]}

        uninstall_packages $noconfirm_flag ${package_names[@]} \
            && install_packages $noconfirm_flag ${package_names[@]}

        disable_packages ${local_disabled_packages[@]}
    }

}

populate_enabled_disabled_all() {
    disabled_packages=($(list_packages | grep "disabled" | awk '{print $1}'))

    enabled_packages=($(list_packages | grep -v "disabled" | awk '{print $1}'))

    all_snap_packages=($(list_packages | awk '{print $1}'))
}

list_packages() {
    # unset flag variables before match, for safety
    local unset noconfirm_flag \
        skipped_command_input \
        all_flag \
        enabled_flag \
        disabled_flag \
        non_snap_flag \

    #
    # Capture flags
    #
    for arg in "${@}";
    do
        case $arg in
            "--non-snap" | "-N")
                [[ -n "$non_snap_flag" ]] && {
                    echo -e "\n - [ERROR] duplicated the 'non-snap' flag - \n"
                    exit 1
                }
                local non_snap_flag=true
            ;;
            "--enabled" | "-e")
                [[ -n "$enabled_flag" ]] && {
                    echo -e "\n - [ERROR] duplicated the 'enabled' flag - \n"
                    exit 1
                }
                local enabled_flag=true
            ;;
            "--disabled" | "-d")
                [[ -n "$disabled_flag" ]] && {
                    echo -e "\n - [ERROR] duplicated the 'disabled' flag - \n"
                    exit 1
                }
                local disabled_flag=true
            ;;
            *) 
                [[ "$arg" == "list" && -z "$skipped_command_input" ]] && {
                    skipped_command_input=true
                    continue
                }

                local package_names+=($arg)
            ;;
        esac
    done

    [[ $non_snap_flag == true ]] && {
        snap_packages=($(snap list | awk '{print $1}'))

        grep_args=""
        for package in ${snap_packages[@]}
        do
            grep_args+="-e \"$package\" "
        done
        
        eval "pacman -Q | grep -v $grep_args" && exit 0 || {
            echo -e "\n - [ERROR] Failed to list pacman packages with \`pacman -Q\`- \n"
            exit 1
        }
    }

    # Loop over each row of the snapper list output containing "snap__"
    sudo snapper -c ${CONFIGS[0]} list | grep "snap__" | while IFS= read -r line
    do
        # Only output packages that have pre and post snapshots
        [[ "$(echo $line | awk -F '|' '{print $2}' )" == " post " ]] && {
            # Grabs the snapshot description
            package_name=$(echo $line | awk -F '|' '{print $7}' | sed 's/snap__//')
            { which $package_name || type $package_name || pacman -Q $package_name; } &>/dev/null && {
                [[ $disabled_flag == true ]] || {
                    readarray -t package_version_array_output < <(pacman -Q $package_name)
                    echo " $package_version_array_output" | tr '[:upper:]' '[:lower:]'
                }
            } || {
                [[ $enabled_flag == true ]] || {
                    printf "%-20s %-1s\n" "$package_name" "[disabled]" | tr '[:upper:]' '[:lower:]'
                }
            }
        }
    done
}


case $1 in
    "list")       check_packages; list_packages $@;;
    "install")    check_packages; install_packages $@;;
    "uninstall")  check_packages; uninstall_packages $@;;
    "disable")    check_packages; disable_packages $@;;
    "enable")     check_packages; enable_packages $@;;
    "upgrade")    check_packages; upgrade_packages $@;;
    "version"|"--version") echo "0.1.0";;
    ""|"--help"|"-h") display_help;;
    *) 
        echo -e "\n - [ERROR] Invalid use of the \`snap\` command -";
        display_help
        exit 1
        ;;
esac
