#!/bin/python3
#
# timehelp - part of the Arch-Setup project
# Copyright (C) 2023, Scott Wyman, development@scottwyman.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

'''
 Takes in time differences & spits out the total.
  Example)
    $ timehelp 4:39-8:00 9:05-10:57 13:50-15:48
    $ 7:11
'''

import sys

total_minutes = 0

# Take in time as arguments
for raw_time in sys.argv[1:]:
    if ":" not in raw_time:
        exit("Time must be formatted as so -> 16:32-17:25")

    start, end = raw_time.split('-')
    
    try:
        # Split by the colon & convert all to minutes
        start = int(start.split(':')[0])*60 + int(start.split(':')[1])
        end = int(end.split(':')[0])*60 + int(end.split(':')[1])
    except ValueError:
        exit("Time must be formatted as so -> 16:32-17:25")


    
    total_minutes += end-start

# Convert back to hour:minute & print to user 
print(f"{int(total_minutes/60)}:{total_minutes%60}")
