#!/bin/bash
#
# vm - part of the Arch-Setup project
# Copyright (C) 2023, Scott Wyman, development@scottwyman.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


#
# Simple to use CLI tool combining some abilities from `virt-manager`,
#  `virt-viewer`(optional), and `virsh` to make managing VMs from the 
#   terminal easy
#

# Check that the required packages are installed
required_packages=(virsh virt-manager)

for package in ${required_packages[@]}; do 
    $package --version &>/dev/null \
        || { echo -e "\n - [ERROR] $package must be installed - \n"; missing_packages=true; } 
done

[[ $missing_packages = true ]] && exit 3


declare -A vm_states=()

parse_vm_states() {
    running=$(virsh list --state-running | awk 'NR > 2 { print $2 }')
    paused=$(virsh list --state-paused | awk 'NR > 2 { print $2 }')
    saved=$(virsh list --all --with-managed-save | awk 'NR > 2 { print $2 }' )
    off=$(virsh list --inactive --without-managed-save | awk 'NR > 2 { print $2 }')
}

populate_vm_states() {
    parse_vm_states

    for vm_name in $running; do
        vm_states[$vm_name]="running"
    done

    for vm_name in $paused; do
        vm_states[$vm_name]="paused"
    done

    for vm_name in $saved; do
        vm_states[$vm_name]="saved"
    done

    for vm_name in $off; do
        vm_states[$vm_name]="off"
    done
}

open_vm() {
    populate_vm_states

    # unset flag variables before match, for safety
    unset fullscreen_virt_viewer_flag \
        virt_viewer_flag \
        vm_names \
        skipped_command_input
    #
    # Capture flags
    #
    for arg in "${@}";
    do
        case $arg in
            "--virt-viewer" | "-V")
                [[ -n "$virt_viewer_flag" ]] && {
                    echo -e "\n - [ERROR] duplicated virt-viewer flag - \n"
                    exit 1
                }

                virt-viewer --version &>/dev/null \
                    && virt_viewer_flag='-V' \
                    || { echo -e "\n - [ ERROR ] virt-viewer not installed - \n"; exit 3; } 
            ;;
            "--fullscreen" | "-f")
                [[ -n "$fullscreen_virt_viewer_flag" ]] && {
                    echo -e "\n - [ERROR] duplicated fullscreen flag - \n"
                    exit 1
                }
                [[ -n "$virt_viewer_flag" ]] \
                    && fullscreen_virt_viewer_flag="-f" \
                    || {
                        echo -e "\n - [ERROR] can only open VM in fullscreen with virt-viewer - \n"
                        exit 1
                    } 
            ;;
            *) 
                [[ "$arg" == "open" && -z "$skipped_command_input" ]] && {
                    skipped_command_input=true
                    continue
                }
                vm_names+=($arg)
            ;;
        esac
    done

    [[ -z ${vm_names[@]} ]] && {
        echo -e "\n - [ERROR] must pass at least one VM name - \n"
        exit 1
    }

    for vm_name in ${vm_names[@]}; do
        [[ -n "${vm_states[$vm_name]}" ]] || { 
            echo -e "\n - [ERROR] VM '$vm_name' Doesn't exist - \n"
            exit 2
        } 

        [[ -n "$virt_viewer_flag" ]] && {
            nohup virt-viewer -a $fullscreen_virt_viewer_flag "$vm_name" \
                &> /tmp/${vm_name}_virt_viewer.log &
            echo "virt-viewer stdin and stdout will be written to /tmp/${vm_name}_virt_viewer.log"
        } || virt-manager -c qemu:///session --show-domain-console "$vm_name"
    done
}

save_vm() {
    populate_vm_states

    # unset flag variables before match, for safety
    unset save_to_file_flag \
        vm_names \
        skipped_command_input \
        save_to_file_flag \
        file_path
    #
    # Capture flags
    #
    for arg in "${@}";
    do
        case $arg in
            "--file" | "-F")
                [[ -n "$save_to_file_flag" ]] && {
                    echo -e "\n - [ERROR] duplicated file flag - \n"
                    exit 1
                }
                save_to_file_flag=true
            ;;
            *) 
                [[ "$arg" == "save" && -z "$skipped_command_input" ]] && {
                    skipped_command_input=true
                    continue
                }
                [[ "$save_to_file_flag" == "true" && -z "$file_path" ]] && {
                    file_path="$arg"
                    continue
                }

                vm_names+=($arg)
            ;;
        esac
    done

    [[ -z ${vm_names[@]} ]] && {
        echo -e "\n - [ERROR] must pass at least one VM name - \n"
        exit 1
    }
    
    [[ ${#vm_names[@]} > 1 && -n "$file_path" ]] && {
        echo -e "\n - [ERROR] Cannot pass multiple VM names while manually setting file path - \n"
        exit 1
    }

    for vm_name in ${vm_names[@]}; do
        [[ -n "${vm_states[$vm_name]}" ]] || {
            echo -e "\n - [ERROR] VM '$vm_name' Doesn't exist - \n"
            exit 2
        }

        [[ "${vm_states[$vm_name]}" == "running" || "${vm_states[$VM_NAME]}" == "paused" ]] && {
            [[ $save_to_file_flag == true && -n "$file_path" ]] \
                && virsh save --verbose $vm_name $file_path \
                || virsh managedsave --verbose $vm_name
        } || { 
            echo -e "\n - [ERROR] Cannot save VM if it's not running or paused - \n"
            exit 1
        }
    done
}

display_help() {
    echo -e "\nUsage: vm [COMMAND]"
    echo -e "\nAbstracts commands from virsh, virt-manager, and"
    echo -e " optionally virt-viewer, to more easily manage Virtual"
    echo -e " Machines from the terminal.\n"

    echo "Commands:"
    printf "\t%-15s %-1s\n" "list" "List the VMs and their states"
    printf "\t%-15s %-1s\n" "start" "Start one or more saved or off VMs"
    printf "\t%-15s %-1s\n" "open" "Open one or more VMs with virt-manager or virt-viewer"
    printf "\t%-15s %-1s\n" "save" "Save one or more VM states"
    printf "\t%-15s %-1s\n" "is-running" "Returns 0 if the VMs are running, otherwise returns 1"
    printf "\t%-15s %-1s\n" "version" "Returns version information"

    echo -e "\nCommand Flags:\n"
    echo -e "\tstart:"
    printf "\t    %-20s\t %-1s\n" "-o | --open" "Open the VM with virt-manager"
    printf "\t    %-20s\t %-1s\n" "-V | --virt-viewer" "If the open flag is passed, open with virt-viewer instead of virt-manager"
    printf "\t    %-20s\t %-1s\n" "-f | --fullscreen" "If the open flag is passed, and virt-viewer is being used, open in fullscreen"
    printf "\t    %-20s\t %-1s\n" "-F | --file" "Restore VM from a manually saved VM state file. No other flags or VM names should be passed with this"
    echo -e "\topen:"
    printf "\t    %-20s\t %-1s\n" "-V | --virt-viewer" "Open with virt-viewer instead of virt-manager"
    printf "\t    %-20s\t %-1s\n" "-f | --fullscreen" "If using virt-viewer, open in fullscreen"
    echo -e "\tsave:"
    printf "\t    %-20s\t %-1s\n" "-F | --file" "Manually save VM state to a file. Only the VM name and location should be passed at once."

    echo -e "\nExamples:"
    echo -e "\t\`vm list\`"
    echo -e "\t\`vm start <vm_name1> <vm_name2>\`"
    echo -e "\t\`vm start --open --virt-viewer <vm_name1> <vm_name2>\`"
    echo -e "\t\`vm start -o -V <vm_name1>\`"
    echo -e "\t\`vm start -f </some/path/vm_save_file.save>\`"
    echo -e "\t\`vm open -V <vm_name1> <vm_name2>\`"
    echo -e "\t\`vm save <vm_name1>\`"
    echo -e "\t\`vm save <vm_name1> -f </some/path/vm_save_file.save>\`"
    echo -e "\t\`vm is-running <vm_name1> <vm_name2> && echo 'running!'\`"

    echo -e "\nError Codes:"
    printf "\t%-3s %-1s\n" "1" "Invalid command (also used to indicate VM not running for the \`is-running\` command."
    printf "\t%-3s %-1s\n" "2" "VM doesn't exist"
    printf "\t%-3s %-1s\n" "3" "Missing dependencies"
}

list_vms() {
    parse_vm_states

    # Print the header
    printf "\n %-30s   %-10s\n" "Name" "State"
    echo "------------------------------------------"

    # Print running VMs
    for vm_name in $running; do
        printf " %-30s   %-10s\n" "$vm_name" "running"
    done

    # Print running VMs
    for vm_name in $paused; do
        printf " %-30s   %-10s\n" "$vm_name" "paused"
    done

    # Print saved VMs
    for vm_name in $saved; do
        printf " %-30s   %-10s\n" "$vm_name" "saved"
    done

    # Print off VMs
    for vm_name in $off; do
        printf " %-30s   %-10s\n" "$vm_name" "off"
    done
}

start_vm() {
    populate_vm_states

    # unset flag variables before match, for safety
    unset open_flag \
        virt_viewer_flag \
        fullscreen_virt_viewer_flag \
        vm_names \
        skipped_command_input \
        restore_from_file_flag \
        file_path
    #
    # Capture flags
    #
    for arg in "${@}";
    do
        case $arg in
            "--file" | "-F")
                [[ -n "$save_to_file_flag" ]] && {
                    echo -e "\n - [ERROR] duplicated file flag - \n"
                    exit 1
                }
                restore_from_file_flag=true
            ;;
            "--open" | "-o")
                [[ -n "$open_flag" ]] && {
                    echo -e "\n - [ERROR] duplicated open flag - \n"
                    exit 1
                }
                open_flag=true
            ;;
            "--virt-viewer" | "-V")
                [[ -n "$virt_viewer_flag" ]] && {
                    echo -e "\n - [ERROR] duplicated virt-viewer flag - \n"
                    exit 1
                }

                [[ -z "$open_flag" ]] && { 
                    echo -e "\n - [ERROR] must pass open flag to use virt-viewer - \n"
                    exit 1
                }

                virt-viewer --version &>/dev/null \
                    && virt_viewer_flag='-V' \
                    || { echo -e "\n - [ERROR] virt-viewer not installed - \n"; exit 3; } 
            ;;
            "--fullscreen" | "-f")
                [[ -n "$fullscreen_virt_viewer_flag" ]] && {
                    echo -e "\n - [ERROR] duplicated fullscreen flag - \n"
                    exit 1
                }
                [[ -n "$virt_viewer_flag" && -n "$open_flag" ]] \
                    && fullscreen_virt_viewer_flag="-f" \
                    || { 
                        echo -e "\n - [ERROR] full screen requires the virt-viewer and open flags - \n"
                        exit 1
                    } 
            ;;
            *) 
                [[ "$arg" == "start" && -z "$skipped_command_input" ]] && {
                    skipped_command_input=true
                    continue
                }

                [[ "$restore_from_file_flag" == "true" && -z "$file_path" ]] && {
                    file_path="$arg"
                    continue
                }

                vm_names+=($arg)
            ;;
        esac
    done

    # file path is only used to restore from file, so no VM name is needed
    #  ! Subject to change to allow other flags
    [[ -n "$file_path" && -f "$file_path" && -n "${vm_names[@]}" ]] || {
        [[ $restore_from_file_flag == true && -n "$file_path" ]] && {
            virsh restore "$file_path"
            exit 0
        }
    } && {
        echo -e "\n - [ERROR] file path - \n"
        exit 1
    }

    [[ -z ${vm_names[@]} ]] && {
        echo -e "\n - [ERROR] must pass at least one VM name - \n"
        exit 1
    }

    for vm_name in ${vm_names[@]}; do
        [[ -n "${vm_states[$vm_name]}" ]] || {
            echo -e "\n - [ERROR] VM '$vm_name' Doesn't exist - \n"
            exit 2
        }

        [[ "${vm_states[$vm_name]}" = "saved" ]] && {
            virsh restore ~/.config/libvirt/qemu/save/$vm_name.save \
                && virsh managedsave-remove "$vm_name" # Only remove if the restore works 
        } || {
            [[ "${vm_states[$vm_name]}" = "off" ]] && virsh start "$vm_name" || {
                echo -e "\n - [ERROR] VM not in an off or saved state, so it cannot be started - \n"
                exit 1
            }
        }

        #
        # Apply Flags
        #
        [[ $open_flag == true ]] \
            && open_vm $virt_viewer_flag $fullscreen_virt_viewer_flag $vm_name
    done
}

check_is_running() {
    populate_vm_states

    # unset flag variables before match, for safety
    unset vm_names \
        skipped_command_input

    for arg in "${@}"; do
        case $arg in
            *) 
                [[ "$arg" == "is-running" && -z "$skipped_command_input" ]] && {
                    skipped_command_input=true
                    continue
                }
                vm_names+=($arg)
            ;;
        esac
    done

    [[ -z ${vm_names[@]} ]] && {
        echo -e "\n - [ERROR] must pass at least one VM name - \n"
        exit 1
    }
   
    for vm_name in ${vm_names[@]}; do
        [[ -n "${vm_states[$vm_name]}" ]] || { 
            echo -e "\n - [ERROR] VM '$vm_name' Doesn't exist - \n"
            exit 2
        }

        [[ "${vm_states[$vm_name]}" != "running" ]] && {
            exit 1
        }
    done

    exit 0
}

case $1 in
    "list")  list_vms;;
    "start") start_vm $@;;
    "open")  open_vm $@;;
    "save")  save_vm $@;;
    "is-running") check_is_running $@;;
    "version"|"--version") echo "0.1.0";;
    ""|"--help"|"-h") display_help;;
    *) 
        echo -e "\n - [ERROR] Invalid use of the \`vm\` command -";
        display_help
        exit 1
        ;;
esac
