#!/bin/bash
#
# notes - part of the Linux-Setup project
# Copyright (C) 2024-2026, JustScott, development@justscott.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

PACKED_NOTES_BASENAME="packed_notes"

REQUIRED_COMMANDS=(printf age tar gzip gunzip)

ensure_commands_installed()
{
    for cmd in ${REQUIRED_COMMANDS[@]}
    do
        if ! command -v $cmd &>/dev/null
        then
            printf "\n\n\e[31m%s %s\e[0m\n\n" \
                "[!] Missing required command: '$cmd'."
            return 1
        fi
    done

    return 0
}

ensure_commands_installed || exit $?

ensure_notes_dir() {
    if [[ -d "${HOME}/notes" ]]
    then
        return 0
    else
        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
            "'${HOME}/notes' directory must exist. Stopping."
        return 1
    fi
}

display_help() {
    printf "\nUsage: notes [COMMAND]"
    printf "\n%s %s\n" \
        "Easy management of encrypted notes in the terminal. Uses \`lf\`" \
        "for note traversal"

    printf "\nCommands:"
    printf "\n  %-12s %s" "pack" \
        "Compress and encrypt '\$HOME/notes' into a packed_notes.tar.gz.age file"
    printf "\n  %-12s %s" "unpack" \
        "Decrypt and decompress packed_notes.tar.gz.age into the '\$HOME/notes' directory"

    printf "\n\nExamples:"
    printf "\n  \`notes\` # opens notes in lf"
    printf "\n  \`notes pack\`"
    printf "\n  \`notes unpack\`\n"
}

encrypt()
{
    filename="$1"

    for attempt in {1..5}
    do
        if [[ $attempt -ne 1 ]]
        then
            printf "\n%s \e[36m%s\e[0m %s\n" "Attempt" "$attempt" "of 5"
        fi

        age --passphrase "${filename}.tar.gz" > "${filename}.tar.gz.age"

        if [[ $? == 0 ]]
        then
            return 0
        else
            printf "\n\n\e[31m%s\e[0m %s\n\n" "[Error]" \
                "Encryption failed... try again"
        fi
    done

    return 1
}

pack() {
    if [[ -f "${PACKED_NOTES_BASENAME}.tar.gz.age" ]] \
    then
        cp "${PACKED_NOTES_BASENAME}.tar.gz.age" \
            "${PACKED_NOTES_BASENAME}.tar.gz.age.bak" &>/dev/null
    fi

    printf "\n\e[36m%s\e[0m %s\n" "Compressing notes..."
    if tar --create --gzip --directory="$HOME" \
        --file="${PACKED_NOTES_BASENAME}.tar.gz" notes &>/dev/null
    then
        printf "\n\e[36m%s\e[0m %s\n" "Encrypt notes:"
        if encrypt "${PACKED_NOTES_BASENAME}"
        then
            rm "${PACKED_NOTES_BASENAME}.tar.gz"
            printf "\n\e[32m%s\e[0m %s\n" "[Success]" \
                "File packed to: ${PACKED_NOTES_BASENAME}.tar.gz.age"
            return 0
        else
            printf "\n\e[31m%s\e[0m %s %s\n" "[Error]" \
                "Couldn't encrypt compressed notes file:" \
                "'${PACKED_NOTES_BASENAME}.tar.gz'"
        fi
    else
        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
            "Couldn't compress '${HOME}/notes' with tar. Stopping."
        return 1
    fi

    if [[ -f "${PACKED_NOTES_BASENAME}.tar.gz.age.bak" ]]
    then
        cp "${PACKED_NOTES_BASENAME}.tar.gz.age.bak" \
            "${PACKED_NOTES_BASENAME}.tar.gz.age" &>/dev/null
    fi
    return 0
}

decrypt()
{
    filename="$1"

    for attempt in {1..5}
    do
        if [[ $attempt -ne 1 ]]
        then
            printf "\n%s \e[36m%s\e[0m %s\n" "Attempt" "$attempt" "of 5"
        fi

        age --decrypt "${filename}.tar.gz.age" > "${filename}.tar.gz"

        if tar --list --file="${PACKED_NOTES_BASENAME}.tar.gz" &>/dev/null
        then
            return 0
        else
            printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
                "Incorrect decryption key... try again"
        fi
    done
        
    return 1
}

unpack() {
    if ! [[ -f ${PACKED_NOTES_BASENAME}.tar.gz.age ]]
    then
        echo "No '${PACKED_NOTES_BASENAME}.tar.gz.age' file found, exiting..."
        return 1
    fi

    if [[ -d "${HOME}/notes" ]]
    then
        printf "\n\e[31m%s\e[0m %s\n" "Error" \
            "'${HOME}/notes' already exists. Stopping."
        return 1
    fi

    if decrypt "${PACKED_NOTES_BASENAME}"
    then
        printf "\n\e[32m%s\e[0m %s\n" "[Success]" \
            "File decrypted to: ${PACKED_NOTES_BASENAME}.tar.gz"
    else
        printf "\n\e[31m%s\e[0m %s %s\n" "[Error]" \
            "Couldn't decrypt encrypted notes files:" \
            "'${PACKED_NOTES_BASENAME}.tar.gz.age'"
        return 1
    fi

    if tar --extract --directory="$HOME" \
        --file="${PACKED_NOTES_BASENAME}.tar.gz" &>/dev/null
    then
        rm "${PACKED_NOTES_BASENAME}.tar.gz" &>/dev/null
        printf "\n\e[32m%s\e[0m %s\n" "[Success]" \
            "Unpacked: '$PACKED_NOTES_BASENAME.tar.gz'"
        return 0
    else
        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
            "Failed to decompress the decrypt '$PACKED_NOTES_BASENAME.tar.gz' file"
        return 1
    fi
}

open_notes() {
    if command -v lf &>/dev/null
    then
        lf $HOME/notes
    else
        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
            "Must have 'lf' installed to traverse notes"
        return 1
    fi

    return 0
}




case $1 in
    "pack")        ensure_notes_dir && pack $@;;
    "unpack")      unpack;;
    "")            ensure_notes_dir && open_notes;;
    "--help"|"-h") display_help;;
    *)
        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
            "Invalid use of the \`notes\` command"
        display_help
        exit 1
        ;;
esac
