#!/bin/bash
#
# store - part of the Linux-Setup project
# Copyright (C) 2024-2026, JustScott, development@justscott.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

PACKED_STORE_BASENAME="packed_store"
PASS_STORE_DIR="$HOME/.password-store"

REQUIRED_COMMANDS=(printf age tar gzip gunzip)

ensure_commands_installed()
{
    for cmd in ${REQUIRED_COMMANDS[@]}
    do
        if ! command -v $cmd &>/dev/null
        then
            printf "\n\n\e[31m%s %s\e[0m\n\n" \
                "[!] Missing required command: '$cmd'."
            return 1
        fi
    done

    return 0
}

ensure_commands_installed || exit $?

ensure_store_dir() {
    if [[ -d $PASS_STORE_DIR ]]
    then
        return 0
    else
        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
            "'$PASS_STORE_DIR' directory must exist. Stopping."
        return 1
    fi
}

display_help() {
    printf "\nUsage: store [COMMAND]"
    printf "\n%s\n" \
        "Easy encrypted backup of your password store and its correlated gpg keys."

    printf "\nCommands:"
    printf "\n  %-12s %s" "pack" \
        "Compress and symmetrically encrypt '\$Home/.password-store' and its correlating asymmetric keys."
    printf "\n  %-12s %s" "unpack" \
        "Decrypt and decompress passwords back into '\$Home/.password-store' and import asymmetric keys"

    printf "\n\nExamples:"
    printf "\n  \`store pack\`"
    printf "\n  \`store unpack\`\n"
}

encrypt()
{
    filename="$1"

    for attempt in {1..5}
    do
        if [[ $attempt -ne 1 ]]
        then
            printf "\n%s \e[36m%s\e[0m %s\n" "Attempt" "$attempt" "of 5"
        fi

        age --passphrase "${filename}.tar.gz" > "${filename}.tar.gz.age"

        if [[ $? == 0 ]]
        then
            return 0
        else
            printf "\n\n\e[31m%s\e[0m %s\n\n" "[Error]" \
                "Encryption failed... try again"
        fi
    done

    return 1
}

pack() {
    printf "\n\e[36m%s\e[0m %s\n" "Unlock password store:"
    gpg_key_id="$(cat "${PASS_STORE_DIR}/.gpg-id")"
    gpg --output "${PASS_STORE_DIR}/public.asc" --batch --yes --armor --export "$gpg_key_id"
    gpg --output "${PASS_STORE_DIR}/private.asc" --batch --yes --armor --export-secret-key "$gpg_key_id"

    if [[ -f "${PACKED_STORE_BASENAME}.tar.gz.age" ]] \
    then
        cp "${PACKED_STORE_BASENAME}.tar.gz.age" \
            "${PACKED_STORE_BASENAME}.tar.gz.age.bak" &>/dev/null
    fi

    printf "\n\e[36m%s\e[0m %s\n" "Compressing store..."
    if tar --create --gzip --directory="$HOME" \
        --file="${PACKED_STORE_BASENAME}.tar.gz" .password-store &>/dev/null
    then
        printf "\n\e[36m%s\e[0m %s\n" "Encrypt store:"
        if encrypt "${PACKED_STORE_BASENAME}"
        then
            rm "${PACKED_STORE_BASENAME}.tar.gz"
            printf "\n\e[32m%s\e[0m %s\n" "[Success]" \
                "File packed to: ${PACKED_STORE_BASENAME}.tar.gz.age"
            return 0
        else
            printf "\n\e[31m%s\e[0m %s %s\n" "[Error]" \
                "Couldn't encrypt compressed notes file:" \
                "'${PACKED_STORE_BASENAME}.tar.gz'"
        fi
    else
        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
            "Couldn't compress '$PASS_STORE_DIR' with tar. Stopping."
        return 1
    fi

    if [[ -f "${PACKED_STORE_BASENAME}.tar.gz.age.bak" ]]
    then
        cp "${PACKED_STORE_BASENAME}.tar.gz.age.bak" \
            "${PACKED_STORE_BASENAME}.tar.gz.age" &>/dev/null
    fi
    return 0
}

decrypt()
{
    filename="$1"

    for attempt in {1..5}
    do
        if [[ $attempt -ne 1 ]]
        then
            printf "\n%s \e[36m%s\e[0m %s\n" "Attempt" "$attempt" "of 5"
        fi

        age --decrypt "${filename}.tar.gz.age" > "${filename}.tar.gz"

        if tar --list --file="${PACKED_STORE_BASENAME}.tar.gz" &>/dev/null
        then
            return 0
        else
            printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
                "Incorrect decryption key... try again"
        fi
    done
        
    return 1
}

unpack() {
    if ! [[ -f "${PACKED_STORE_BASENAME}.tar.gz.age" ]]
    then
        echo "No '${PACKED_STORE_BASENAME}.tar.gz.age' file found, exiting..."
        return 1
    fi

    if [[ -d "$PASS_STORE_DIR" ]]
    then
        printf "\n\e[31m%s\e[0m %s\n" "Error" \
            "'$PASS_STORE_DIR' already exists. Stopping."
        return 1
    fi

    if decrypt "${PACKED_STORE_BASENAME}"
    then
        printf "\n\e[32m%s\e[0m %s\n" "[Success]" \
            "File decrypted to: ${PACKED_STORE_BASENAME}.tar.gz"
    else
        printf "\n\e[31m%s\e[0m %s %s\n" "[Error]" \
            "Couldn't decrypt encrypted notes files:" \
            "'${PACKED_STORE_BASENAME}.tar.gz.age'"
        return 1
    fi

    if tar --extract --directory="$HOME" \
        --file="${PACKED_STORE_BASENAME}.tar.gz" &>/dev/null
    then
        rm "${PACKED_STORE_BASENAME}.tar.gz" &>/dev/null
        printf "\n\e[32m%s\e[0m %s\n" "[Success]" \
            "Unpacked: '$PACKED_STORE_BASENAME.tar.gz'"
    else
        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
            "Failed to decompress the decrypt '$PACKED_STORE_BASENAME.tar.gz' file"
        return 1
    fi

    gpg --import "${PASS_STORE_DIR}/private.asc" \
        "${PASS_STORE_DIR}/public.asc" &>/dev/null
    if [[ $? -ne 0 ]]
    then
        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
            "Failed to import private and public keys. Stopping."
        return 1
    fi

    printf "\n\e[32m%s\e[0m %s\n" "[Success]" \
        "Imported private and public keys"

    rm "${PASS_STORE_DIR}/private.asc" "${PASS_STORE_DIR}/public.asc"

    gpg_key_id="$(cat "${PASS_STORE_DIR}/.gpg-id")"
    # Set ultimate trust non-interactively (use full fingerprint!)
    echo "$gpg_key_id:6:" | gpg --import-ownertrust &>/dev/null
    if [[ $? -ne 0 ]]
    then
        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
            "Failed to set 'ultimate' trust level on imported keys."
        return 1
    fi

    printf "\n\e[32m%s\e[0m %s\n" "[Success]" \
        "Set keys trust level to 'ultimate'"

    return 0
}


case $1 in
    "pack")        ensure_store_dir && pack $@;;
    "unpack")      unpack;;
    " "|"--help"|"-h") display_help;;
    *)
        echo -e "\n - Invalid use of the \`store\` command -";
        display_help
        exit 1
        ;;
esac
