#!/bin/bash
#
# brightness - part of the Arch-Setup project
# Copyright (C) 2023-2025, JustScott, development@justscott.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


brightness() {
    screen_status=$(brightnessctl i)
    if echo "$screen_status" | grep -e "Current brightness: 1 (" -e "input1::numlock" &>/dev/null
    then 
        return 1
    else 
        echo "$screen_status" | grep "Current" | awk '{print $4}' | sed 's/(//; s/)//'
    fi
}

if which brightnessctl &>/dev/null
then
    brightness
fi
