#!/bin/bash
#
# disconnect-external-displays - part of the Arch-Setup project
# Copyright (C) 2023-2025, JustScott, development@justscott.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


# 
# Turn on main display and turn off all external displays
#

main_display=$(wlr-randr | grep "eDP-" | awk '{print $1}')

wlr-randr --output $main_display --on --pos 0,0

external_displays=$(wlr-randr | grep "^DP-" | awk '{print $1}')

for display in ${external_displays[@]}
do
    wlr-randr --output $display --off
done
