#!/bin/bash
#
# restart-creek - part of the Arch-Setup project
# Copyright (C) 2023, Scott Wyman, development@scottwyman.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


creek_PID=($(top -n 1 -b | grep "creek" | grep "$USER" | awk '{print $1}'))

echo -e -n "\nKilling existing creek processes..."
for pid in ${creek_PID[@]}
do
    kill -9 $pid
done
echo "[ Done ]"


echo -n "Restarting Creek..."
while true;
do
    sleep 1
    cat /tmp/status_bar_info
done | creek \
        -fn monospace:size=16 -hg 28 -nf 0xffffff \
        -nb 0x222222 -ff 0xffffff -fb 0x005577 &
echo -e "[ Done ]\n"
