#!/bin/bash
#
# restart-creek - part of the Arch-Setup project
# Copyright (C) 2023-2025, JustScott, development@justscott.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

LOG_FILE_PATH=$HOME/.tmp/status_bar_info

creek_PID=($(top -U $USER -n 1 -b | grep "creek" | awk '{print $1}'))

echo -e -n "\nKilling existing creek processes..."
for pid in ${creek_PID[@]}
do
    kill -9 $pid
done
echo "[ Done ]"

mkdir -p $(dirname $LOG_FILE_PATH)

echo -n "Restarting Creek..."
while true;
do
    sleep 1
    cat $LOG_FILE_PATH
done | creek $(cat $HOME/.river_creek_theme) &
echo -e "[ Done ]\n"
