#!/bin/bash
#
# start-pulseaudio-server - part of the Arch-Setup project
# Copyright (C) 2023-2025, JustScott, development@justscott.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


start-pulseaudio-server() {
    pamixer --get-volume &>/dev/null || {
        pulseaudio --kill &>/dev/null
        pulseaudio --start &>/dev/null
    }
}

if which pamixer &>/dev/null
then
    start-pulseaudio-server
fi
